"""
Django settings for iseries project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'z%u*^3cc(8q2z1w7f-_z#xm#(%d5ms4b6)@orpn@-bown)1+3c'
SECRET_KEY = 'hhjePnz8CDxHxF08oLolLNjUk5us7QPx3gDASElddUkyuDLWrK3JVoJau7PAGOp121srTnBffFgAMTda2443f0V8w7eA1goor0Bp'
#SESSION_ENGINE = 'django.contrib.sessions.backends.db'
#SESSION_SERIALIZER = 'iseries.serializers.PickleSerializer'
#SESSION_COOKIE_DOMAIN = ".myopenedx.com"
#AUTH_USER_MODEL = 'auth.User'
#AUTH_PROFILE_MODULE = 'accounts.UserProfile'
#PREVENT_CONCURRENT_LOGINS = False
#SITE_ID = 1
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    
    
    #'channels',
    
    #'cart',
    'dashboard.apps.DashboardConfig',
    
    
    'accounts.apps.AccountsConfig',
    
    'tinymce',
    'mathfilters',
    'pages.apps.PagesConfig',
    'contacts.apps.ContactsConfig',
    'siteconf.apps.SiteconfConfig',
    'series',
    'admin_volt.apps.AdminVoltConfig',
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
   
 ]
ASGI_APPLICATION = 'iseries.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('192.168.1.3', 6379)],
        },
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
  #  'iseries.middleware.SafeSessionMiddleware.SafeSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#SILENCED_SYSTEM_CHECKS = [
#    'admin.E408',
#    'admin.E409',
#    'admin.E410',
#]

#AUTHENTICATION_BACKENDS = (
#    'django.contrib.auth.backends.AllowAllUsersModelBackend',
#    'userena.backends.UserenaAuthenticationBackend',
#    'guardian.backends.ObjectPermissionBackend',
#)
ROOT_URLCONF = 'iseries.urls'

#ANONYMOUS_USER_NAME = 'AnonymousUser'

#AUTH_PROFILE_MODULE = 'accounts.UserProfile'
# USERENA_SIGNIN_REDIRECT_URL = '/accounts/%(username)s/'
#USERENA_SIGNIN_REDIRECT_URL ='/dashboard'
#LOGIN_URL = '/accounts/signin/'
#LOGOUT_URL = '/accounts/signout/'
#LOGOUT_REDIRECT_URL = "/"
#USERENA_ACTIVATION_REQUIRED = True
#USERENA_WITHOUT_USERNAMES = True
#USERENA_SIGNIN_AFTER_SIGNUP = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'cart.context_processor.cart_total_amount',
                'siteconf.processor.secret',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iseries.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#DATABASES = {
#   'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'openedx',
#         'USER': 'root',
#         'PASSWORD': 'N1XecB9O',
         #'HOST': '172.16.0.7',
#         'HOST': '192.168.1.6',
#         'PORT': '3306',
#     },
#     'seconder': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
#}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
EDX_HOST='http://myopenedx.com'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CART_SESSION_ID = 'cart'


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'iseries/static')
]

# Media Folder

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'
# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'
    
}
