# Generated by Django 4.1.4 on 2022-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=270)),
                ('job', models.CharField(max_length=270)),
                ('body', models.CharField(max_length=270)),
                ('avatar', models.ImageField(upload_to='testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='TopSiteConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_white', models.ImageField(blank=True, upload_to='media/logos')),
                ('logo_normal', models.ImageField(blank=True, upload_to='media/logos')),
                ('telephone', models.CharField(blank=True, default=-9999444, max_length=20)),
                ('work_time', models.CharField(blank=True, default='Mon-Sun 07:00-19:00', max_length=270)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com/th3d1gger', max_length=270)),
                ('facebook', models.CharField(blank=True, default='https://facebook.com', max_length=270)),
                ('linkedin', models.CharField(blank=True, default='https://linkedin.com', max_length=270)),
                ('instagram', models.CharField(blank=True, default='https://instagram.com', max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('content', models.CharField(max_length=270)),
            ],
        ),
    ]
