# Generated by Django 4.1.4 on 2022-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatcherSociallink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('social_link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'watcher_sociallink',
                'managed': False,
            },
        ),
    ]
