# Generated by Django 4.1.4 on 2022-12-26 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(blank=True, max_length=270)),
                ('facebook', models.CharField(blank=True, max_length=270)),
                ('instagram', models.CharField(blank=True, max_length=270)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(upload_to='2XNFwhGXPPbAJEQcbMDfAxFAueLM9Koi/%Y/%m/%d/')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
