# Generated by Django 4.1.4 on 2022-12-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='zqnmxSvJcakffukSAKJdRQYH3cOwbd2r/%Y/%m/%d/'),
        ),
    ]
