# Generated by Django 4.1.4 on 2022-12-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='wUz0lMY2m7Eel24iBvYwvCIOCjQTiwYt/%Y/%m/%d/'),
        ),
    ]
