# Generated by Django 4.1.4 on 2022-12-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='G85LvPcUj1fKoik3Y4mE7R4mW6iejcCc/%Y/%m/%d/'),
        ),
    ]
