# Generated by Django 4.1.4 on 2022-12-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='9OzuZnQmn1nyOYGNo1znfyxL6Hcy4kdv/%Y/%m/%d/'),
        ),
    ]
