# Generated by Django 4.1.4 on 2022-12-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='vnVg0e1rnhZJ28X855uILqycH273MQie/%Y/%m/%d/'),
        ),
    ]
