# Generated by Django 4.1.4 on 2022-12-26 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='teacher',
        ),
        migrations.AddField(
            model_name='serie',
            name='teacher',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
